version: '3.7'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    container_name: app
    depends_on:
      - mongodb
      - redis
    environment:
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
      - MONGODB_USERNAME=root
      - MONGODB_PASSWORD=root
      - JWT_SECRET=dockerSecret
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  mongodb:
    image: mongo:5.0.0
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=todoapp
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db

  redis:
    image: redis:6.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data_container:/data

volumes:
  mongodb_data_container:
  redis_data_container: