version: '3.7'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    container_name: app
    depends_on:
      - mongodb

  mongodb:
    image: mongo:5.0.0
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=todoapp
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container: